services:
  db:
    image: postgres:15-alpine
    container_name: korpbot_postgres_db
    restart: always
    # Эти значения будут браться из файла .env
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    ports:
      - "5434:5432" # Вы сможете подключиться к БД с компьютера по порту 5434
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER} -d ${DB_NAME}"]
      interval: 5s
      timeout: 5s
      retries: 5

  bot:
    build: .
    container_name: korpbot_telegram_bot
    restart: always
    command: python main.py
    environment:
      # Правильная строка подключения, которая берет данные из .env и указывает на сервис 'db'
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
      - BOT_TOKEN=${BOT_TOKEN}
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy # Запустится только когда БД будет готова

  api:
    build: .
    container_name: korpbot_fastapi_api
    restart: always
    command: uvicorn app:app --host 0.0.0.0 --port 8000 --reload
    environment:
      - DATABASE_URL=postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@db:5432/${DB_NAME}
    ports:
      - "8000:8000"
    volumes:
      - .:/app
    depends_on:
      db:
        condition: service_healthy

volumes:
  postgres_data: